#!/usr/bin/env python3
"""Generates the launcher icon (coffee mug with steam) from one set of shapes.

Writes:
  app/src/main/res/drawable/ic_launcher_foreground.xml  (cream mug, transparent; also the monochrome layer)
  app/src/main/res/drawable/ic_launcher_background.xml  (terracotta gradient)
  app/src/main/res/drawable/ic_mug.xml                   (the same mug as a tintable 24dp in-app icon)
  docs/store/icon-512.png                                (Play Store icon, full bleed square)

Edit the shapes here, not the generated files. Coordinates are in the 108 x 108 adaptive-icon
viewport; the glyph stays inside the central 66dp safe zone. Needs Pillow for the PNG.
"""
import re
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "app/src/main/res/drawable"

CREAM = "#F8EFE3"
BG_TOP, BG_BOTTOM = "#BA6C4D", "#A45A3D"

# Path data uses only M, L, H, V, C, Z (absolute) so the PNG renderer can flatten it.
SHAPES = {
    "Mug body": "M42.4,50 C42.4,49.56 42.76,49.2 43.2,49.2 H64.8 C65.24,49.2 65.6,49.56 65.6,50 "
                "V73.2 C65.6,74.75 64.35,76 62.8,76 H45.2 C43.65,76 42.4,74.75 42.4,73.2 Z",
    "Handle": "M65.6,52.2 H68.6 C71.6,52.2 74,54.6 74,57.6 V64.6 C74,67.6 71.6,70 68.6,70 H65.6 "
              "V67.3 H68.6 C70.1,67.3 71.3,66.1 71.3,64.6 V57.6 C71.3,56.1 70.1,54.9 68.6,54.9 H65.6 Z",
    "Steam, center": None,
    "Steam, left": None,
    "Steam, right": None,
}


def wisp(x0, y0, x1, y1, amplitude, width, n=14):
    """A tapered S-shaped ribbon from (x0, y0) down to (x1, y1), as an L-only path."""
    import math
    left, right = [], []
    for k in range(n + 1):
        t = k / n
        x = x0 + (x1 - x0) * t + amplitude * math.sin(2 * math.pi * t)
        y = y0 + (y1 - y0) * t
        half = width / 2 * math.sin(math.pi * t) ** 0.7
        left.append((x - half, y)); right.append((x + half, y))
    pts = left + right[::-1]
    return "M" + " L".join(f"{x:.2f},{y:.2f}" for x, y in pts) + " Z"


SHAPES["Steam, center"] = wisp(52.4, 31.8, 53.8, 47.3, 1.7, 2.7)
SHAPES["Steam, left"] = wisp(47.2, 37.7, 49.6, 46.4, 1.3, 2.3)
SHAPES["Steam, right"] = wisp(57.2, 35.1, 58.0, 44.7, 1.3, 2.3)


def argb(hex_color):
    return "#FF" + hex_color[1:]


def write_xml():
    paths = "\n".join(
        f'    <!-- {name} -->\n    <path\n        android:fillColor="{argb(CREAM)}"\n        android:pathData="{d}" />'
        for name, d in SHAPES.items()
    )
    (RES / "ic_launcher_foreground.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/icon/launcher_icon.py: edit the script, not this file.\n"
        "     Launcher icon: a steaming mug, the break you get back. Single color, so it also works as\n"
        "     the themed (monochrome) icon. Inside the 66dp safe zone. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n    android:height="108dp"\n'
        '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
        f"{paths}\n</vector>\n"
    )
    (RES / "ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/icon/launcher_icon.py: edit the script, not this file.\n"
        "     Launcher icon background: warm terracotta, slightly lighter toward the top. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp"\n    android:height="108dp"\n'
        '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        "            <gradient\n"
        '                android:type="linear"\n'
        '                android:startX="54"\n                android:startY="0"\n'
        '                android:endX="54"\n                android:endY="108"\n'
        f'                android:startColor="{argb(BG_TOP)}"\n'
        f'                android:endColor="{argb(BG_BOTTOM)}" />\n'
        "        </aapt:attr>\n    </path>\n</vector>\n"
    )


def write_mug_icon():
    """In-app icon (Home header): the glyph re-centered in a 48 x 48 viewport, tinted by the caller."""
    paths = "\n".join(
        f'        <path\n            android:fillColor="#FF000000"\n            android:pathData="{d}" />'
        for d in SHAPES.values()
    )
    (RES / "ic_mug.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/icon/launcher_icon.py: edit the script, not this file.\n"
        "     A steaming mug, tinted by the caller (Icon / LocalContentColor). -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n    android:height="24dp"\n'
        '    android:viewportWidth="48"\n    android:viewportHeight="48">\n'
        '    <group android:translateX="-34.2" android:translateY="-29.9">\n'
        f"{paths}\n    </group>\n</vector>\n"
    )


def flatten(d, scale, steps=24):
    tokens = re.findall(r"[MLHVCZ]|-?\d*\.?\d+", d)
    pts, i, cur, cmd = [], 0, (0.0, 0.0), None
    num = lambda: float(tokens.pop(0))
    while tokens:
        if re.fullmatch(r"[MLHVCZ]", tokens[0]):
            cmd = tokens.pop(0)
        if cmd == "M" or cmd == "L":
            cur = (num(), num()); pts.append(cur)
        elif cmd == "H":
            cur = (num(), cur[1]); pts.append(cur)
        elif cmd == "V":
            cur = (cur[0], num()); pts.append(cur)
        elif cmd == "C":
            p1, p2, p3 = (num(), num()), (num(), num()), (num(), num())
            for k in range(1, steps + 1):
                t = k / steps; u = 1 - t
                pts.append((u**3 * cur[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0],
                            u**3 * cur[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1]))
            cur = p3
        elif cmd == "Z":
            pass
    return [(x * scale, y * scale) for x, y in pts]


def rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))


def write_png(size=512, ss=4):
    big = size * ss
    img = Image.new("RGB", (big, big))
    top, bottom = rgb(BG_TOP), rgb(BG_BOTTOM)
    draw = ImageDraw.Draw(img)
    for y in range(big):
        t = y / (big - 1)
        draw.line([(0, y), (big, y)], fill=tuple(round(a + (b - a) * t) for a, b in zip(top, bottom)))
    for d in SHAPES.values():
        draw.polygon(flatten(d, big / 108), fill=rgb(CREAM))
    out = ROOT / "docs/store/icon-512.png"
    img.resize((size, size), Image.LANCZOS).save(out)


if __name__ == "__main__":
    write_xml()
    write_mug_icon()
    write_png()
    print("ok")
